import FBMessanger from "@/components/FBMessanger/FBMessanger";
// import { CartProvider } from "@/utils/Cart/CartContext";
// import { QueryProvider } from "@/utils/QueryClientProvider";
// import AuthProvider from "@/utils/SessionProvider";
// import { Toaster } from "react-hot-toast";
import './globals.css'


export const metadata = {
  title: "Kishorgonj Keshba Fazil Madrasha",
  description: "Generated by Sifat",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <AuthProvider> */}
          {/* <QueryProvider>
            <CartProvider> */}
              <div>
                {children}
              </div>
            {/* </CartProvider>
          </QueryProvider> */}
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
